name: Comprehensive DevSecOps Pipeline (SAST, SCA, DAST)

on:
  pull_request:
    branches: [ main, master ]
  push:
    branches: [ main, master ]

permissions:
  # This permission is required when uploading sarifs to any repository at GitHub
  security-events: write
  # These permissions are only required when uploading sarifs to private and internal repositories at GitHub
  contents: read
  actions: read
jobs:
  # ===============================================
  # JOB 1: SAST (Static Analysis - Code Quality)
  # ===============================================
  sast_job:
    name: semgrep-SAST
    runs-on: ubuntu-latest
    container:
      image: semgrep/semgrep
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
    
      - name: Run Semgrep SAST Scan (Code Analysis)
        run : semgrep ci --config auto --sarif > semgrep.sarif   
      
      - name: Upload SARIF file for GitHub Advanced Security Dashboard
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: semgrep.sarif
        if: always()    

    # Skip any PR created by dependabot to avoid permission issues:
    if: (github.actor != 'dependabot[bot]')  
    
  secret_example:
    name: secret-example
    runs-on: ubuntu-latest
    steps:
    - shell: bash
      env:
        SUPER_SECRET: ${{ secrets.A_SECRET }}
      run: |
        echo "✅ GOOD WAY (never printed) -->"
        echo $SUPER_SECRET > super-secret.txt
        echo "⛔ BAD WAY (Fixed by SECRET MASKING) -->"
        echo $SUPER_SECRET | tee super-secret2.txt
  sca_job:
    name: trivy-SCA
    runs-on: ubuntu-latest
    #needs: sast_job # This job must wait for SAST to complete successfully
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        
      # Setup Python and Install dependencies are repeated because SCA runs on a fresh runner
      - name: Set up Python Environment and Install Dependencies
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      
      - name: Install Application Dependencies
        run: pip install -r requirements.txt
        working-directory: . # Assumes requirements.txt is in the root

      - name: Run Trivy SCA Scan (Dependency Check)
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          input: '.' # Scan the entire filesystem (where requirements.txt was processed)
          # Policy: Fail the build if Critical or High severity vulnerabilities are found
          exit-code: '1'
          severity: 'CRITICAL,HIGH'
          # Output SARIF for GitHub Security Dashboard integration
          format: 'sarif'
          output: 'trivy-sca.sarif'

      - name: Upload SARIF file for GitHub Advanced Security Dashboard
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: trivy-sca.sarif
        if: always() 
